- name: Add gpg key for syncthing
  apt_key:
    url: https://syncthing.net/release-key.gpg
    keyring: /usr/share/keyrings/syncthing-archive-keyring.gpg
    state: present

- name: Add syncthing apt repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
    state: present
    update_cache: true
    filename: syncthing

- name: Install syncthing
  apt:
    name: syncthing
    state: present

- name: Enable syncthing service
  service:
    name: syncthing@fraccs.service
    state: started
    enabled: true
