- name: Install docker requirements
  become: true
  vars:
    packages:
      - ca-certificates
      - curl
      - gnupg
  apt:
    name: "{{ packages }}"

- name: Add docker gpg key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    update_cache: true

- name: Install docker
  become: true
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  apt:
    name: "{{ packages }}"
