- name: Add apt signing key for Google Chrome
  become: true
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub

- name: Add Google Chrome repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
    update_cache: true

- name: Install Google Chrome
  become: true
  apt:
    name: google-chrome-stable
