- name: Add apt signing key for Google Chrome
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
- name: Add Google Chrome repository
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome
- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: present
    update_cache: true
