- name: Install gdb
  become: true
  apt:
    name: gdb

- name: Clone gef
  git:
    repo: https://github.com/hugsy/gef
    dest: /home/fraccs/Apps/gef

- name: Create gdb-gef script
  become: true
  copy:
    dest: /usr/bin/gdb-gef
    mode: o+x
    content: |
      #!/bin/sh
      exec gdb -q -ex init-gef "$@"

- name: Clone pwndbg
  git:
    repo: https://github.com/pwndbg/pwndbg
    dest: /home/fraccs/Apps/pwndbg

- name: Install pwndbg
  become: true
  shell:
    cmd: cd /home/fraccs/Apps/pwndbg && ./setup.sh

- name: Create gdb-pwndbg script
  become: true
  copy:
    dest: /usr/bin/gdb-pwndbg
    mode: o+x
    content: |
      #!/bin/sh
      exec gdb -q -ex init-pwndbg "$@"

- name: Clone peda
  git:
    repo: https://github.com/longld/peda.git
    dest: /home/fraccs/Apps/peda

- name: Create gdb-peda script
  become: true
  copy:
    dest: /usr/bin/gdb-peda
    mode: o+x
    content: |
      #!/bin/sh
      exec gdb -q -ex init-peda "$@"

- name: Write gdb configuration
  become: true
  copy:
    dest: /etc/gdb/gdbinit
    content: |
      define init-gef
      source /home/fraccs/Apps/gef/gef.py
      end
      document init-gef
      Initializes GEF (GDB Enhanced Features)
      end

      define init-pwndbg
      source /home/fraccs/Apps/pwndbg/gdbinit.py
      end
      document init-pwndbg
      Initializes PwnDBG
      end

      define init-peda
      source /home/fraccs/Apps/peda/peda.py
      end
      document init-peda
      Initializes the PEDA (Python Exploit Development Assistant for GDB) framework
      end
