- name: Install gdb
  become: true
  apt:
    name: gdb

- name: Stat if gef is cloned
  stat:
    path: ~/Apps/gef
  register: gef

- name: Clone gef
  git:
    repo: https://github.com/hugsy/gef
    dest: ~/Apps/gef
  when: not gef.stat.exists

- name: Stat if gdb-gef exists
  stat:
    path: /usr/bin/gdb-gef
  register: gdb_gef

- name: Create gdb-gef script
  become: true
  copy:
    dest: /usr/bin/gdb-gef
    mode: o+x
    content: |
      #!/bin/sh
      exec gdb -q -ex init-gef "$@"
  when: not gdb_gef.stat.exists

- name: Stat if pwndbg is cloned
  stat:
    path: ~/Apps/pwndbg
  register: pwndbg

- name: Clone pwndbg
  git:
    repo: https://github.com/pwndbg/pwndbg
    dest: ~/Apps/pwndbg
  when: not pwndbg.stat.exists

- name: Install pwndbg
  become: true
  shell:
    cmd: cd /home/fraccs/Apps/pwndbg && ./setup.sh
  when: not pwndbg.stat.exists

- name: Stat if gdb-pwndbg exists
  stat:
    path: /usr/bin/gdb-pwndbg
  register: gdb_pwndbg

- name: Create gdb-pwndbg script
  become: true
  copy:
    dest: /usr/bin/gdb-pwndbg
    mode: o+x
    content: |
      #!/bin/sh
      exec gdb -q -ex init-pwndbg "$@"
  when: not gdb_pwndbg.stat.exists

- name: Stat if peda is cloned
  stat:
    path: ~/Apps/peda
  register: peda

- name: Clone peda
  git:
    repo: https://github.com/longld/peda.git
    dest: ~/Apps/peda
  when: not peda.stat.exists

- name: Stat if gdb-peda exists
  stat:
    path: /usr/bin/gdb-peda
  register: gdb_peda

- name: Create gdb-peda script
  become: true
  copy:
    dest: /usr/bin/gdb-peda
    mode: o+x
    content: |
      #!/bin/sh
      exec gdb -q -ex init-peda "$@"
  when: not gdb_peda.stat.exists

- name: Write gdb configuration
  become: true
  copy:
    dest: /etc/gdb/gdbinit
    content: |
      define init-gef
      source /home/fraccs/Apps/gef/gef.py
      end
      document init-gef
      Initializes GEF (GDB Enhanced Features)
      end

      define init-pwndbg
      source /home/fraccs/Apps/pwndbg/gdbinit.py
      end
      document init-pwndbg
      Initializes PwnDBG
      end

      define init-peda
      source /home/fraccs/Apps/peda/peda.py
      end
      document init-peda
      Initializes the PEDA (Python Exploit Development Assistant for GDB) framework
      end
