- name: Install gcc
  apt:
    name: gcc
    state: present

- name: Install g++
  apt:
    name: g++
    state: present

- name: Install libc6
  apt:
    name: libc6
    state: present

- name: Install libc6-dev
  apt:
    name: libc6-dev
    state: present
