- name: Install JDK
  apt:
    name: openjdk-17-jdk
    state: present

- name: Install JRE
  apt:
    name: openjdk-17-jre
    state: present

- name: Install maven
  apt:
    name: maven
    state: present
