- name: Install tor daemon
  become: true
  apt:
    name: tor
    state: latest

- name: Download tor browser
  get_url:
    url: https://dist.torproject.org/torbrowser/12.5.3/tor-browser-linux64-12.5.3_ALL.tar.xz
    dest: /tmp/tor-browser-linux64-12.5.3_ALL.tar.xz

- name: Import tor browser developers key
  become: true
  shell:
    cmd: gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org
  register: gpg_output

- name: Export tor browser developers key to file
  become: true
  shell:
    cmd: gpg --output /tmp/tor.keyring --export 0xEF6E286DDA85EA2A4BA7DE684E2C6E8793298290

- name: Download tor browser signature
  get_url:
    url: https://www.torproject.org/dist/torbrowser/12.5.3/tor-browser-linux64-12.5.3_ALL.tar.xz.asc
    dest: /tmp/tor-browser-linux64-12.5.3_ALL.tar.xz.asc

- name: Verify tor browser signature
  become: true
  shell:
    cmd: gpgv --keyring /tmp/tor.keyring /tmp/tor-browser-linux64-12.5.3_ALL.tar.xz.asc /tmp/tor-browser-linux64-12.5.3_ALL.tar.xz

- name: Extract tor browser
  become: true
  unarchive:
    src: /tmp/tor-browser-linux64-12.5.3_ALL.tar.xz
    dest: /opt
    owner: fraccs

- name: Install tor browser
  shell:
    cmd: cd /opt/tor-browser && ./start-tor-browser.desktop --register-app
