- name: Download ghidra
  get_url:
    url: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3.3_build/ghidra_10.3.3_PUBLIC_20230829.zip
    dest: /tmp/ghidra_10.3.3_PUBLIC_20230829.zip

- name: Extract ghidra
  unarchive:
    src: /tmp/ghidra_10.3.3_PUBLIC_20230829.zip
    dest: /home/fraccs/Apps

- name: Rename extracted ghidra directory
  command:
    cmd: mv /home/fraccs/Apps/ghidra_10.3.3_PUBLIC /home/fraccs/Apps/ghidra

- name: Download ghidra icon
  get_url:
    url: https://github.com/NationalSecurityAgency/ghidra/files/3853902/ghidra_ico.zip
    dest: /tmp/ghidra_ico.zip

- name: Extract ghidra icon
  unarchive:
    src: /tmp/ghidra_ico.zip
    dest: /home/fraccs/Apps/ghidra/support

- name: Create ghidra application launcher
  become: true
  copy:
    dest: /usr/share/applications/ghidra.desktop
    content: |
      [Desktop Entry]
      Encoding=UTF-8
      Name=Ghidra
      Exec=/home/fraccs/Apps/ghidra/ghidraRun
      Icon=/home/fraccs/Apps/ghidra/support/ghidra.ico
      Type=Application
      Categories=Reversing;
