- name: Download ghidra
  get_url:
    url: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3.3_build/ghidra_10.3.3_PUBLIC_20230829.zip
    dest: /tmp/ghidra_10.3.3_PUBLIC_20230829.zip

- name: Extract ghidra
  unarchive:
    src: /tmp/ghidra_10.3.3_PUBLIC_20230829.zip
    dest: /opt
    owner: fraccs

- name: Ensure that ghidra was extracted
  stat:
    path: /opt/ghidra_10.3.3_PUBLIC
  register: ghidra_stat

- name: Rename extracted ghidra directory
  command:
    cmd: mv /opt/ghidra_10.3.3_PUBLIC /opt/ghidra
  when: ghidra_stat.stat.exists

- name: Download ghidra icon
  get_url:
    url: https://github.com/NationalSecurityAgency/ghidra/files/3853902/ghidra_ico.zip
    dest: /tmp/ghidra_ico.zip

- name: Extract ghidra icon
  unarchive:
    src: /tmp/ghidra_ico.zip
    dest: /opt/ghidra/support
    owner: fraccs

- name: Create ghidra application launcher
  copy:
    dest: /usr/share/applications/ghidra.desktop
    content: |
      [Desktop Entry]
      Encoding=UTF-8
      Name=Ghidra
      Exec=/opt/ghidra/ghidraRun
      Icon=/opt/ghidra/support/ghidra.ico
      Type=Application
      Categories=Reversing;
