---
- name: Setup desktop (Ubuntu 22.04)
  hosts: localhost
  roles:
    - act
    - binwalk
    - bitwarden
    - bun
    - burpsuite
    - c
    - chrome
    - curl
    - discord
    - docker
    - elfutils
    - exiftool
    - ffmpeg
    - firefox
    - gdb
    - ghidra
    - git
    - gparted
    - ht
    - htop
    - ida
    - iriun
    - java
    - ltrace
    - make
    - mtp
    - nmap
    - nodejs
    - nvidia
    - obsidian
    - patchelf
    - pwntools
    - pycryptodome
    - pyshark
    - python
    - raspberrypi
    - ropper
    - ruby
    - spotify
    - syncthing
    - tor
    - typescript
    - vim
    - vscode
    - wget
    - wireshark
