---
- name: Setup desktop (ubuntu)
  hosts: localhost
  become: true
  vars:
    apt_packages_to_install:
      - build-essential
      - cmake
      - curl
      - default-jdk
      - default-jre
      - nvidia-driver-525
      - gcc
      - gdb
      - git
      - htop
      - make
      - maven
      - python3
      - python3-pip
      - vim
      - wget
    snap_packages_to_install:
      - discord
      - spotify
    snap_classic_packages_to_install:
      - code
    snap_packages_to_remove:
      - firefox
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
    - name: Install apt packages
      apt:
        name: "{{ apt_packages_to_install }}"
        state: present
    - name: Install snap packages
      community.general.snap:
        name: "{{ snap_packages_to_install }}"
    - name: Install snap (classic) packages
      community.general.snap:
        name: "{{ snap_classic_packages_to_install }}"
        classic: true
    - name: Remove snap packages
      community.general.snap:
        name: "{{ snap_packages_to_remove }}"
    - name: Add apt signing key for Google Chrome
      apt_key:
        url: "https://dl.google.com/linux/linux_signing_key.pub"
        state: present
    - name: Add Google Chrome repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome
    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present
        update_cache: true
