---
- name: Setup laptop (Ubuntu 22.04)
  hosts: localhost
  become: true
  roles:
    - act
    - binwalk
    - bitwarden
    - burpsuite
    - c
    - chrome
    - curl
    - discord
    - docker
    - elfutils
    - firefox
    - gdb
    - ghidra
    - git
    - gparted
    - ht
    - htop
    - java
    - ltrace
    - make
    - mtp
    - nodejs
    - obsidian
    - patchelf
    - pwntools
    - pycryptodome
    - pyshark
    - python
    - ropper
    - ruby
    - spotify
    - syncthing
    - tor
    - typescript
    - vim
    - vscode
    - wget
    - wireshark
