---
- name: Setup laptop (Ubuntu 22.04)
  hosts: localhost
  roles:
    - act
    - binwalk
    - bitwarden
    - bun
    - burpsuite
    - c
    - chrome
    - curl
    - discord
    - dnsutils
    - docker
    - elfutils
    - exiftool
    - ffmpeg
    - firefox
    - gdb
    - ghidra
    - git
    - gparted
    - ht
    - htop
    - ida
    - java
    - ltrace
    - make
    - mtp
    - nmap
    - nodejs
    - obsidian
    - patchelf
    - pwntools
    - pycryptodome
    - pyshark
    - python
    - qemu-kvm
    - raspberrypi
    - ropper
    - ruby
    - spotify
    - syncthing
    - tor
    - typescript
    - vim
    - vscode
    - wget
    - wireguard
    - wireshark
