---
- name: Setup laptop (Ubuntu 22.04)
  hosts: localhost
  become: true
  roles:
    - act
    - bitwarden
    - c
    - chrome
    - curl
    - discord
    - docker
    - gdb
    - git
    - htop
    - java
    - make
    - nodejs
    - obsidian
    - python
    - spotify
    - tor
    - typescript
    - vim
    - vscode
    - wget
